### ISSUE TITLE
Editing journal entry after using view command does not update the main viewing panel

### ISSUE THREAD

**Issue by joshualiangxy** [AY2021S1-CS2103T-W17-4/tp#164]
Steps to replicate:
1. `view in/j index/ANY_VALID_INDEX`
![image](https://user-images.githubusercontent.com/28984700/97540844-2c913200-19ff-11eb-826b-5743416b5915.png)
2. `editj 1 ANY_VALID_EDITS`
![image](https://user-images.githubusercontent.com/28984700/97540942-50547800-19ff-11eb-9bc0-0953e5eddba5.png)
3. The list of entries is reset to the full list, but the main viewing panel is not updated.
![image](https://user-images.githubusercontent.com/28984700/97541010-68c49280-19ff-11eb-9ded-558cafdec32e.png)

**Comment by zhXchD** [comment]
This is caused by `model.updateFilteredEntryList(PREDICATE_SHOW_ALL_ENTRIES)` in `EditJournalEntryCommand.java`. Commenting out this line will solve the issue.

I will make a PR for `v.1.4` to change the sidebar selection behavior as well as to solve this issue.
